baseURL = "https://blog.ceshine.net/"
languageCode = "en"
title = "Veritable Tech Blog"
theme = "cactus-plus"
Paginate = 5
googleAnalytics = "G-HE2HBKGF2H"
hasCJKLanguage = false

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[params]
   author = "Ceshine Lee"
   bio = "Technical Notes from a Data Geek."
   description = "Veritable Tech Blog"
   twitter = "ceshine_en"
   enableRSS = true
   enableToc = true
   enableDisqus = true
   disqusShortname = "ceshine-lis-blog"
   githubName = "ceshine"
   pygmentsUseClassic = false
   pygmentsCodeFencesGuessSyntax = true

   enableSummary = true
	# Set the value to true if use description in post front matter replace content summary
	useDescriptionReplaceSummary = true

	enableGoogleAnalytics = true
   enableBaiduAnalytics = false

   enableTwitterCard = true
   enableShare = true

	# Navigation links
	home = ""
	archive = ""

   # show latest posts in single page
	showLatestPosts = false
   readMore = ""

   # 404 page
	title404 = ""
   subtitle404 = ""

   # Choose a font for the social icons in the footer. Either "mono-social" or "font-awesome"
   iconFont = "font-awesome"
   # The social icons can be styled differently if you use mono as font - circle, rounded, or empty
   socialIconStyle = "square"

# Add additional social link entries underneath
[social]
    twitter-square  = "https://www.twitter.com/ceshine_en"
    github-square   = "https://www.github.com/ceshine"