services:
  content:
    build:
      context: dockerfiles/content
    volumes:
      - hugo_content:/src/blog
  web:
    build:
      context: dockerfiles/hugo
    ports:
      - "80:1313"
    volumes:
      - hugo_content:/src/blog
    restart: on-failure
volumes:
  hugo_content:
